### ISSUE TITLE
Missing try...catch for null case

### ISSUE THREAD

**Issue by mrskynet** [hoangdesu/JAVActress#1]
Seem like this 
<img width="394" alt="Screen Shot 2020-05-04 at 14 06 16" src="https://user-images.githubusercontent.com/5028869/80943125-a9f13680-8e10-11ea-9779-59441db79b37.png">

**Comment by tan-developer** [comment]
> Seem like this
> <img alt="Screen Shot 2020-05-04 at 14 06 16" width="394" src="https://user-images.githubusercontent.com/5028869/80943125-a9f13680-8e10-11ea-9779-59441db79b37.png">

it work with upercase i think

**Comment by mrskynet** [comment]
I have just updated code here:
https://repl.it/join/lhgvxokp-mrskynet
When your actress is null, must keep end user try to typing again.  Same with video_id

**Comment by hoangdesu** [comment]
parameter shouldn't include a whitespace, so if you wish to search for such name, try type in either "Yui" or "Hatano" instead. Yeah it's a quick and fun project so I didn't implement a lot of conditional checks
